<?php

 // Auto generated by wpfluent Installer.

return array(
    'name'           => 'Fluent Shipment',
    'slug'           => 'fluentshipment',
    'domain_path'    => '/language',
    'text_domain'    => 'fluentshipment',
    'hook_prefix'    => 'fluentshipment',
    'rest_namespace' => 'fluentshipment',
    'rest_version'   => 'v2',
    'env'            => 'production',
);
